# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(282, 367)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Title = QtWidgets.QWidget(Dialog)
        self.Title.setObjectName("Title")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Title)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.Title)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.Title)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmbMatch = QtWidgets.QComboBox(self.widget)
        self.cmbMatch.setObjectName("cmbMatch")
        self.horizontalLayout.addWidget(self.cmbMatch)
        self.cmbTeam = QtWidgets.QComboBox(self.widget)
        self.cmbTeam.setObjectName("cmbTeam")
        self.horizontalLayout.addWidget(self.cmbTeam)
        self.verticalLayout_3.addWidget(self.widget)
        self.tblScore = QtWidgets.QTableWidget(Dialog)
        self.tblScore.setColumnCount(2)
        self.tblScore.setObjectName("tblScore")
        self.tblScore.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblScore.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblScore.setHorizontalHeaderItem(1, item)
        self.tblScore.horizontalHeader().setCascadingSectionResizes(False)
        self.tblScore.horizontalHeader().setDefaultSectionSize(125)
        self.tblScore.horizontalHeader().setSortIndicatorShown(False)
        self.tblScore.horizontalHeader().setStretchLastSection(True)
        self.tblScore.verticalHeader().setVisible(False)
        self.tblScore.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tblScore)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnCalculate = QtWidgets.QPushButton(self.widget1)
        self.btnCalculate.setObjectName("btnCalculate")
        self.horizontalLayout_3.addWidget(self.btnCalculate)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.widget1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Evaluate the Performance of your fantasy team"))
        item = self.tblScore.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "PLAYER"))
        item = self.tblScore.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "POINTS"))
        self.btnCalculate.setText(_translate("Dialog", "Calculate Score"))
